### ISSUE TITLE
where is the download?

### ISSUE THREAD

**Issue by Boomer-1** [VoperAD/SlimeFrame#2]
Hey Voper, just looking for where to download. you posted that a new version would get pushed, where is it?

**Comment by Boomer-1** [comment]
i finally found it but it was more by accident. if this is where you're pushing the new downloads, i would recommend the jar file be visible on the first page they come to.

**Comment by VoperAD** [comment]
The new version is available for download in [Spigot](https://www.spigotmc.org/resources/slimeframe.111432/). However, new versions will no longer be posted there, which means that the Spigot page for SlimeFrame will remain at version 1.3.1. This is not a big trouble, as the version 1.3.1 includes the new auto update system and two server restarts would be enough for the plugin to detect if there's a new version and update itself, but yea, you are right. I'll update the description so people can find the jar easily.
 
Just in case anyone sees this issue trying to find the download link, all released versions are listed in the [Releases](https://github.com/VoperAD/SlimeFrame/releases) section. If you want the latest version, just check which one has the 'latest' tag and download the JAR, which is within the assets section.

![image](https://github.com/VoperAD/SlimeFrame/assets/92862848/5ec5036d-cc0c-459c-a87d-5613b94e2160)
