### ISSUE TITLE
Suggested change to relics

### ISSUE THREAD

**Issue by Boomer-1** [VoperAD/SlimeFrame#6]
when redeeming void traces, you can upgrade relics to exceptional, flawless or radiant. I am suggesting to change those to match the levels of items the relics can produce. so change exceptional to common, flawless to uncommon and radiant to rare. the current titles of upgraded relics don't point to the actual levels and are a little confusing. this way there's no question what the potential is you will get. right now it's not clear.

same thing in the relics tutorial book. it says bronze, silver and gold, but again, nothing in game indicates that they match up. essentially there's 3 different terms for the exact same thing. please eliminate the confusion and change them so all 3 match up.

**Comment by VoperAD** [comment]
Actually the refinement (intact, exceptional, flawless and radiant) and the type of the reward (common, uncommon and rare) refer to different things. I do agree that the names in the tutorial book (bronze, silver and gold rewards) should be changed to common, uncommon and rare, though.

I'll likely include a description either in the relics tutorial book or in the SF guide to clarify how the chances to receive each reward type change with each refinement level.
