### ISSUE TITLE
DANGEROUS DUPE ANY ITEMS

### ISSUE THREAD

**Issue by balugaq** [VoperAD/SlimeFrame#8]
## Description (Required)
1. Place a Terracotta Generator in a energy net.
2. Prepare the item want to dupe.
3. Select a colored terracotta in the generator and make it work.
4. When the generator working, we can double-left-click to take the item on the select slot.
5. Put the item want to dupe with shift-left-click quickly, or the generator will lose.
6. Wait it working again, then it produced the item we want.

## Steps to reproduce the Issue (Required)

https://github.com/VoperAD/SlimeFrame/assets/129668183/9b06807c-ef14-471b-b343-63cca2050abd

## Expected behavior (Required)
It can't work again. Like Wool Generator.

## Server Log / Error Report
Nothing.

## Environment (Required)
![0dbb50d1b43f6b47f946e354076b4c04](https://github.com/VoperAD/SlimeFrame/assets/129668183/909e0435-b7f7-403d-9292-5221b804614b)

**Comment by VoperAD** [comment]
Thanks for the report, I'll fix it as soon as possible.

**Comment by VoperAD** [comment]
Fixed on version 1.6.2

**Comment by balugaq** [comment]
Ok, thanks. Did you find any other machines with this issue? I did't make sure that's all the machines.

**Comment by VoperAD** [comment]
Yes, every machine with a selector had this issue.
